# Load environment variables from .env file

# Use an official Python image as a base
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the application code
COPY . .

# Expose the port the app will use
EXPOSE ${DJANGO_PORT}

# Run the command to start the development server
CMD ["python", "manage.py", "runserver", "${DJANGO_HOST}:${DJANGO_PORT}"]