# Generated by Django 4.2.13 on 2024-07-17 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ip', models.CharField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'address IP',
                'verbose_name_plural': 'address IPs',
                'db_table': 'server_address_ip',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 7, 18, 19, 38, 38, 226736, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'passwor reset token',
                'verbose_name_plural': 'passwor reset tokens',
                'db_table': 'user_passwor_reset_token',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'db_table': 'server_session',
            },
        ),
        migrations.CreateModel(
            name='ValidEmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 7, 18, 19, 38, 38, 227174, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'valid email token',
                'verbose_name_plural': 'valid email tokens',
                'db_table': 'user_valid_email_token',
            },
        ),
    ]
